---
- name: Install startup script
  hosts: pi
  tasks:
    - name: Copy start-franklin.sh to destination directory
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../scripts/start-franklin.sh"
        dest: "{{ pi_dest_dir }}/start-franklin.sh"
        mode: "0755"
