---
- import_playbook: 00-preflight.yml
- import_playbook: 10-system-packages.yml
- import_playbook: 15-franklin-user.yml
- import_playbook: 20-python-venv.yml
- import_playbook: 30-tmuxinator.yml
- import_playbook: 40-redis.yml
- import_playbook: 45-network-hotspot.yml
- import_playbook: 50-startup-script.yml
- import_playbook: 55-autologin-startup.yml
- import_playbook: 56-wayland-sway.yml
- import_playbook: 57-hdmi-hotplug.yml
- import_playbook: 58-wayvnc.yml
- import_playbook: 60-system-info.yml
